### ISSUE TITLE
The on-screen keyboard opens automatically

### ISSUE THREAD

**Issue by ghost** [MarianArlt/sddm-chili#1]
The problem is that when you click on the password entry area, the on-screen keyboard opens automatically. I use kubuntu 18.04 and plasma 5.12.5. I know that you don't recommend using this version of the theme with plasma, but the default built-in store offers exactly that:
![screenshot_20180615_134307](https://user-images.githubusercontent.com/34649010/41464266-5bbf4cc8-70a2-11e8-9f34-d961208bffb6.png)

**Comment by MarianArlt** [comment]
@sudofail thank you for reporting this behaviour. I will absolutely need to add some code to prevent this from happening. As a work around in the mean time please consider adding the following line to your SDDM configuration file:
```
# /etc/sddm.conf

[General]
...
InputMethod=
...
```
or delete any value it has assigned if the line exists already.

**Comment by MarianArlt** [comment]
@sudofail b02e76237a81bd5473fb6265d37f4a0a928c2852 Should hopefully solve this. I decided to reimplement the original breeze logic for the virtual keyboard. You can just update through the KDE store.
Would be great if you tested this and gave feedback!

**Comment by ghost** [comment]
@MarianArlt, after applying the theme, instead of sddm I see a black screen. Fixed this by editing the theme in sddm.conf, but, now it's another bug. Maybe it's because of the compatibility with the plasma?

**Comment by MarianArlt** [comment]
@sudofail what did you edit in `sddm.conf` to work around the black screen? Also please open a new issue for a new bug. I really want this to work well for anybody! Thank you for you time!

**Comment by ghost** [comment]
@MarianArlt, I just changed the theme to the default one so that I can log in. I think this bug is related to the changes you made to fix the on-screen keyboard. I don't know how this can be tested to say, this problem is only with me and whether it's related to plasma. Any ideas?

**Comment by MarianArlt** [comment]
* Does this also happen when you use [Chili for KDE Plasma](https://github.com/MarianArlt/kde-plasma-chili)?
   * The only symptom is a complete black screen? No response whatsoever?

I tested this theme as working with Arch/Plasma and on another machine with Manjaro/LXQt.
Really sorry for the inconvenience.

**Comment by ghost** [comment]
@MarianArlt, Chili for KDE Plasma works fine. On the black screen I see the mouse cursor and that's it.

**Comment by MarianArlt** [comment]
@sudofail The whole virtual keyboard thing is a very urgent bug in SDDM to begin with found here: https://github.com/sddm/sddm/issues/952 We will have to wait for sddm to fix this and after that see how the themes react to it (all themes have this issue at the moment).
