### ISSUE TITLE
How can I disable the upper case of the first letter in username?

### ISSUE THREAD

**Issue by zjuyk** [MarianArlt/sddm-chili#10]
My first letter is "Z". I think it will be better for "z"

**Comment by zhangkaizhao** [comment]
I guess you can remove this line which capitalizes the username label:
https://github.com/MarianArlt/sddm-chili/blob/0.1.5/components/UserDelegate.qml#L86
```
font.capitalization: Font.Capitalize
```

**Comment by zjuyk** [comment]
Thank you! It works.
