### ISSUE TITLE
How to change date and time format in the upright?

### ISSUE THREAD

**Issue by CtrlValCanc** [MarianArlt/sddm-chili#15]
I would like to put another format, thank you.

**Comment by CtrlValCanc** [comment]
If anyone else is searching, you have to edit [this](https://github.com/MarianArlt/sddm-chili/blob/6516d50176c3b34df29003726ef9708813d06271/Main.qml#L87) line

**Comment by MttCastelli** [comment]
> If anyone else is searching, you have to edit [this](https://github.com/MarianArlt/sddm-chili/blob/6516d50176c3b34df29003726ef9708813d06271/Main.qml#L87) line

You're right, this way I get a 24h format (and also remove a space after comma):

`87                        text = new Date().toLocaleString(Qt.locale("en_US"), "ddd dd MMMM yyyy, HH:mm")
`
