### ISSUE TITLE
Suspend/Reboot/Shutdown Misaligned

### ISSUE THREAD

**Issue by Yaanu** [MarianArlt/sddm-chili#2]
When using Chili, for some reason the clickable areas of the labels for the action buttons (Suspend, Reboot, Shutdown) are misaligned with where they would logically go. The clickable areas are placed above the actual icons, sized proportionately with the labels and completely operational but still unusual.

For reference, I'm on a fresh build of Arch Linux and my Main.qml file is slightly edited to account for my screen's resolution (1366 x 768). Nothing else in the file nor any other QML file has been changed.

**Comment by MarianArlt** [comment]
@Yaanu I made a change to the action buttons mouse area, this fixed the same behavior in the KDE version of the theme so I hope it'll do here as well. a7783d926bd7ea2b7682ea47828d484e3aca8878 Please update to 0.1.2 from within the system settings and let me know!

**Comment by Yaanu** [comment]
@MarianArlt I've updated, but it doesn't seem to work. The issue remains, even before re-editing Main.qml to adjust for my screen resolution.

**Comment by MarianArlt** [comment]
@Yaanu Latest release 0.1.3 has new options and fixed hover areas (tested working). Sorry for the delay!

**Comment by Yaanu** [comment]
No worries! Everything works perfectly now!
