### ISSUE TITLE
dependencies on Arch Linux

### ISSUE THREAD

**Issue by BenjaminDR** [MarianArlt/sddm-chili#5]
On Arch Linux these necessary packages do not come automatically with sddm:

- qt5-quickcontrols
- qt5-graphicaleffects

Might be worth to mention in readme

**Comment by MarianArlt** [comment]
Thank you for pointing out, this is true indeed. Since this is a fork based on the plasma theme it's not mentioned (for completeness I had it earlier, but deleted it and then forked...)
