### ISSUE TITLE
qt5-virtualkeyboard dependency

### ISSUE THREAD

**Issue by ranisalt** [MarianArlt/sddm-chili#8]
Chili imports Qt5.VirtualKeyboard, but it is not mentioned on README. Is it considered optional (since Chili works fine without it) or a mistake?

**Comment by sum01** [comment]
I think it's optional. The Arch wiki mentions SDDM is able to use a virtual keyboard if you install qt5-virtualkeyboard and edit its config, so I assume the same is true for this theme.

**Comment by MarianArlt** [comment]
The Qt virtual keyboard is an optional module by Qt as a means to provide input for touch devices.
SDDM has support for this module by default but ironically does not serve any real implementation. 

The theme designers are responsible for handling this mechanism even if we don't want to support it. If we do not provide a mechanism for it, anybody who had this module installed will have a huge digital keyboard overlay the whole login screen...

Some distros install the virtual keyboard as a recommended dependency for SDDM, so one might have it installed without even noticing it. In your case it was the other way 'round basically. You noticed it getting installed and now wonder why a theme would need this in the first place. I have mentioned this several times by now, it's really annoying for SDDM theme creators.

To be fair though it's on the [roadmap for v0.19](https://github.com/sddm/sddm/milestone/12). Which could be months or years away seeing the developing speed of SDDM.
See [this upstream issue](https://github.com/sddm/sddm/issues/952) for more details.
